package dev.chaya.api.storage;

import java.io.InputStream;
import java.util.List;

/** The raw-media bucket. All keys are generated by the server; callers never pass client input as a key. */
public interface ObjectStore {

    record PartEtag(int partNumber, String etag) {}

    void ensureBucket();

    String beginMultipart(String key, String contentType);

    /** Uploads one part (re-uploading the same part number replaces it) and returns its ETag. */
    String uploadPart(String key, String uploadId, int partNumber, byte[] data);

    void completeMultipart(String key, String uploadId, List<PartEtag> parts);

    void abortMultipart(String key, String uploadId);

    /** Size in bytes of a stored object; throws {@link StorageException} if it does not exist. */
    long size(String key);

    InputStream open(String key);

    void delete(String key);

    /** True if the storage service answers. Used by the health check. */
    boolean ping();
}
