package dev.chaya.api.storage;

import java.io.InputStream;
import java.util.List;

/** The raw-media bucket. All keys are generated by the server; callers never pass client input as a key. */
public interface ObjectStore {

    record PartEtag(int partNumber, String etag) {}

    void ensureBucket();

    String beginMultipart(String key, String contentType);

    /** Uploads one part (re-uploading the same part number replaces it) and returns its ETag. */
    String uploadPart(String key, String uploadId, int partNumber, byte[] data);

    void completeMultipart(String key, String uploadId, List<PartEtag> parts);

    void abortMultipart(String key, String uploadId);

    /** Size in bytes of a stored object; throws {@link StorageException} if it does not exist. */
    long size(String key);

    InputStream open(String key);

    /** Server-side copy within the bucket: the bytes never pass through the API. Replaces the target if it exists. */
    void copy(String sourceKey, String targetKey);

    /** Deleting a key that does not exist succeeds (S3 semantics), so a deletion can always be repeated. */
    void delete(String key);

    /** Every key under the prefix (all pages). Used by erasure and the PII staging sweep to find objects no row names. */
    List<String> list(String prefix);

    /** Aborts every unfinished multipart upload under the prefix, so no uploaded part outlives an erasure. Returns how many. */
    int abortUploads(String prefix);

    /** The SHA-256 (lowercase hex) of an object's bytes, computed by reading all of them. */
    default String sha256(String key) {
        try (InputStream in = open(key)) {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
            byte[] buf = new byte[1 << 16];
            for (int n; (n = in.read(buf)) > 0; ) {
                md.update(buf, 0, n);
            }
            return java.util.HexFormat.of().formatHex(md.digest());
        } catch (java.io.IOException e) {
            throw new StorageException("could not read " + key + " to hash it", e);
        } catch (java.security.NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }

    /** The object's bytes, failing at end of stream unless they hash to {@code expectedSha256} (VerifyingInputStream). */
    default InputStream openVerified(String key, String expectedSha256) {
        return new VerifyingInputStream(open(key), expectedSha256, key);
    }

    /** True if the storage service answers. Used by the health check. */
    boolean ping();
}
